INSERT INTO CUSTOMERS (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY,  PHONE_NUMBER)
VALUES ('Adams', 'Roy', 'radams1v@xinhuanet.com', 'United States',  '1-(235)314-9823');
INSERT INTO CUSTOMERS (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER)
VALUES ('Adams', 'Martin', 'madams2b@msu.edu', 'China',  '9-(401)660-9813');
INSERT INTO CUSTOMERS (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY,  PHONE_NUMBER)
VALUES ('Alvarez', 'Roger', 'ralvarezk@blogs.com', 'United States',  '6-(980)036-6105');
INSERT INTO CUSTOMERS (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER)
VALUES ('Alvarez', 'Anne', 'aalvarez1y@mlb.com', 'United States', '7-(967)349-7237');
INSERT INTO CUSTOMERS (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER)
VALUES ('Alvarez', 'Ann', 'aalvarez20@jalbum.net', 'Afghanistan',  '7-(418)731-2327');
INSERT INTO CUSTOMERS (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY,  PHONE_NUMBER)
VALUES ('Anderson', 'Betty', 'banderson14@digg.com', 'United States',  '1-(291)830-0405');
INSERT INTO CUSTOMERS (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY,  PHONE_NUMBER)
VALUES ('Anderson', 'Laura', 'landerson24@icio.us', 'United States',  '3-(587)240-6409');
INSERT INTO CUSTOMERS (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY,  PHONE_NUMBER)
VALUES ('Armstrong', 'Christopher', 'carmstrong2p@cyberchimps.com', 'United States', '3-(411)160-3757');
INSERT INTO CUSTOMERS (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY,  PHONE_NUMBER)
VALUES ('Bell', 'David', 'dbell2l@wp.com', 'United States',  '8-(035)412-4547');
INSERT INTO CUSTOMERS (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER)
VALUES ('Berry', 'Paula', 'pberry1z@admin.ch', 'China', '6-(195)796-7745');
INSERT INTO CUSTOMERS (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER)
VALUES ('Bishop', 'Dennis', 'dbishopo@xinhuanet.com', 'Armenia',  '4-(871)489-3543');
INSERT INTO CUSTOMERS (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER)
VALUES ('Bishop', 'Carolyn', 'cbishopw@1688.com', 'Ukraine',  '5-(795)729-5690');
INSERT INTO CUSTOMERS (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY,  PHONE_NUMBER)
VALUES ('Black', 'Harold', 'hblack2p@clickbank.net', 'Indonesia',  '0-(378)142-3343');
INSERT INTO CUSTOMERS (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY,  PHONE_NUMBER)
VALUES ('Bowman', 'Jerry', 'jbowman1j@fotki.com', 'Indonesia',  '9-(389)678-8585');
INSERT INTO CUSTOMERS (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, COUNTRY, PHONE_NUMBER)
VALUES ('Bradley', 'Keith', 'kbradley1c@techcrunch.com', 'United States',  '5-(780)609-5353');

